### ISSUE TITLE
Error when executing node app.js

### ISSUE THREAD

**Issue by lokopobit** [garciadelcastillo/Documentos-RNE#1]
I followed your setup instructions. After cloning and installing node.js I opened a terminal in the cloned folder. See screenshot below:

![npm](https://user-images.githubusercontent.com/60197979/79637725-0b16da00-8182-11ea-956b-096e52dc1b68.PNG)

After that I executed node app.js. See screenshot below.

![node](https://user-images.githubusercontent.com/60197979/79637826-7b256000-8182-11ea-823d-af3810ea27a3.PNG)

Thanks.

**Comment by garciadelcastillo** [comment]
Hi! I am not maintaining this repo anymore. Feel free to open a pull request if you find what the issue might be. Thanks!
